skill and feedback connection to user
Daniel12321/CoachEm pull request #17
Opened 2023-03-15 14:02 UTC by gabeplz

2023-03-15 14:19 UTC, Daniel12321 requested changes

2023-03-15 14:19 UTC, Daniel12321 commented on backend/coachem/src/main/java/nl/itvitae/coachem/model/Skill.java
> +@Table(name = "Skill")
Table annotations met hoofdletters deleten

2023-03-15 14:19 UTC, Daniel12321 commented on backend/coachem/src/main/java/nl/itvitae/coachem/model/Skill.java
> +    @JsonInclude(JsonInclude.Include.NON_NULL)
Dit lijkt tegenstrijdig

2023-03-15 14:19 UTC, Daniel12321 commented on backend/coachem/src/main/resources/application.properties
> +14 lines (10 sloc)  641 Bytes
Delete dit bestand nog even

2023-03-15 14:21 UTC, MarkBos83 requested changes

2023-03-15 14:21 UTC, MarkBos83 commented on backend/coachem/src/main/java/nl/itvitae/coachem/controller/SkillController.java
> +    @PutMapping("update/by_id/{id}")
slashje vergetenn

2023-03-15 14:21 UTC, MarkBos83 commented on backend/coachem/src/main/java/nl/itvitae/coachem/model/Skill.java
> +
category

2023-03-16 09:22 UTC, Daniel12321 approved these changes

2023-03-16 09:24 UTC, MarkBos83 approved these changes

2023-03-16 09:24 UTC, merged